[package]
name = "log_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
reqwest = { version = "0.12.28", default-features = false, features = [
    "rustls-tls",
] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
