apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: greeter-dep-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
        - name: v1
          image: tomjtoth/devops-with-kubernetes:greeter-5.3
          env:
            - name: IP
              value: 0.0.0.0
            - name: PORT
              value: "3000"
            - name: MESSAGE
              value: hello from v1

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000

          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: greeter-dep-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v2
  template:
    metadata:
      labels:
        app: greeter
        version: v2
    spec:
      containers:
        - name: v1
          image: tomjtoth/devops-with-kubernetes:greeter-5.3
          env:
            - name: IP
              value: 0.0.0.0
            - name: PORT
              value: "3000"
            - name: MESSAGE
              value: hello from v2

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000

          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
