apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  namespace: exercises
  name: cpu-stress
spec:
  metrics:
    - name: exercises-cpu-usage
      interval: 30s
      count: 10 # 10 * 30s = 5 minutes
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1769-prometheus.prometheus.svc.cluster.local:9090
          query: |
            scalar(sum(rate(container_cpu_usage_seconds_total{namespace="exercises", container!="POD"}[2m])))
      successCondition: result < 1.2
      failureCondition: result >= 1.2
