apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: pvc-100m
        - name: config
          configMap:
            name: log-output-conf

      containers:
        - name: log-output
          image: tomjtoth/devops-with-kubernetes:log-output-3.2
          env:
            - name: LOG_PATH
              value: data/log
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
        - name: log-server
          image: tomjtoth/devops-with-kubernetes:log-server-3.2
          env:
            - name: IP
              value: 0.0.0.0
            - name: PORT
              value: "3000"

            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-conf
                  key: message
            - name: BACKEND_URL
              value: http://pingpong-svc:55555/pings
            - name: LOG_PATH
              value: data/log
          volumeMounts:
            - name: shared-data
              mountPath: /app/data

            - name: config
              mountPath: /app/information.txt
              subPath: information.txt
