apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: pvc-100m
spec:
  storageClassName: pv-100m-project
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
